# Generated by Django 4.1 on 2022-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('text', models.TextField(max_length=10000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('likes', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
